#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OnQAndroid.Resource", IsApplication=true)]

namespace OnQAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::OnQAndroid.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::OnQAndroid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::OnQAndroid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::OnQAndroid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int gpa_array = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int major_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int year_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blackborderwhitebutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkmark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int OnQLogo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int OnQLogoSmall = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pdf2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rectangleborder = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int roundedbutton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int turquoisebutton = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060026
			public const int AdvanceButton = 2131099686;
			
			// aapt resource value: 0x7f060007
			public const int CSIdentify = 2131099655;
			
			// aapt resource value: 0x7f060018
			public const int ConfirmNewPassword = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int FullName = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int LoginButton = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int NewEmail = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int NewPassword = 2131099671;
			
			// aapt resource value: 0x7f060025
			public const int NextButton = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int SelectButton = 2131099687;
			
			// aapt resource value: 0x7f06000e
			public const int SignupButton = 2131099662;
			
			// aapt resource value: 0x7f060029
			public const int SkipButton = 2131099689;
			
			// aapt resource value: 0x7f060008
			public const int TFemail = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int TFpassword = 2131099658;
			
			// aapt resource value: 0x7f060028
			public const int UploadButton = 2131099688;
			
			// aapt resource value: 0x7f060011
			public const int advance = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int cameraButton = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int content_fragment = 2131099651;
			
			// aapt resource value: 0x7f06001f
			public const int emailField = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int facebook = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int finish = 2131099673;
			
			// aapt resource value: 0x7f06000c
			public const int forgotpassword = 2131099660;
			
			// aapt resource value: 0x7f060024
			public const int gpaspinner = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int gradtermPrompt = 2131099681;
			
			// aapt resource value: 0x7f06000f
			public const int imageView1 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int item_subtitle = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int item_title = 2131099667;
			
			// aapt resource value: 0x7f060023
			public const int majorspinner = 2131099683;
			
			// aapt resource value: 0x7f06001e
			public const int nameField = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int photoButton2 = 2131099680;
			
			// aapt resource value: 0x7f060010
			public const int progressBar1 = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int recruiterIdentify = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int sliding_tabs = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int studentIdentify = 2131099653;
			
			// aapt resource value: 0x7f06001c
			public const int studentProfile = 2131099676;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int textView3 = 2131099657;
			
			// aapt resource value: 0x7f060016
			public const int textView4 = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int textView5 = 2131099661;
			
			// aapt resource value: 0x7f06001a
			public const int textView6 = 2131099674;
			
			// aapt resource value: 0x7f060002
			public const int viewpager = 2131099650;
			
			// aapt resource value: 0x7f060022
			public const int yearspinner = 2131099682;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CSBuildProfile = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_sample = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeTab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IdentifyUserType = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoginSignup = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MyQsTab = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int pager_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int passwordRecover = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ProfileTab = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RecruiterBuildProfile = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SettingsTab = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int signupScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int StudentBuildProfile = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SuccessScreen = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int UploadResume = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int gpa_prompt = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int major_prompt = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int year_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
